server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
    contextPath: /
  port: '8080'
logging:
  level:
    org:
      springframework:
        boot: INFO
        security: DEBUG
      apache:
        tiles: INFO
        web: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    com:
      samsung:
        security: DEBUG
    root: INFO
#jasypt:
  #encryptor:
  #  bean: jasyptStringEncryptor


spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
      use-new-id-generator-mappings: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database: mysql
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: rldya2tony!
      username: root
    url: jdbc:mysql://localhost:3306/ssafy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  devtools:
    livereload:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
build:
  date: '@build.date@'
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'






